Repository duszka-akos-attila/c_sharp_mechanicWorkshop, pull requests merged in 2021-05, with the labels that each got.

#20 Backend API Endpoints 2
  Server/API/Controllers/JobController.cs
  Server/API/Dto/JobUpdateDto.cs
  Server/API/Exception/JobNotFoundException.cs
  Server/API/Repositories/JobRepository.cs
Labels: backend

#23 Backend refactor
  Server/API.Tests/API.Tests.csproj
  Server/API.Tests/JobControllerUnitTests.cs
  Server/API.Tests/Properties/AssemblyInfo.cs
  Server/API.Tests/packages.config
  Server/API/Controllers/JobController.cs
  Server/API/Persistance/Models/Job.cs
  Server/API/Persistance/Repositories/JobContext.cs
  Server/API/Persistance/Repositories/JobRepository.cs
  Server/API/Repositories/JobRepository.cs
  Server/API/Service/Dto/JobDto.cs
  Server/API/Service/Dto/JobListDto.cs
  Server/API/Service/Exception/JobNotFoundException.cs
  Server/API/Service/IJobService.cs
  Server/API/Service/Implementation/JobService.cs
  Server/API/Startup.cs
  Server/Server.Tests/Properties/AssemblyInfo.cs
  Server/Server.Tests/Server.Tests.csproj
  Server/Server.Tests/UnitTest1.cs
  Server/Server.Tests/packages.config
  Server/ServerTest/Properties/AssemblyInfo.cs
  Server/ServerTest/ServerTest.csproj
  Server/ServerTest/UnitTest1.cs
  Server/ServerTest/packages.config
Labels: backend

#24 Backend test
  Server/API.Test/API.Test.csproj
  Server/API.Test/JobControllerTest.cs
  Server/API.Tests/API.Tests.csproj
  Server/API.Tests/JobControllerUnitTests.cs
  Server/API.Tests/Properties/AssemblyInfo.cs
  Server/API.Tests/packages.config
  Server/API/Controllers/JobController.cs
  Server/API/Persistance/Models/Job.cs
  Server/API/Service/Dto/JobDto.cs
  Server/API/Service/Dto/JobListDto.cs
  Server/Commons/Commons.csproj
  Server/Server.Tests/Properties/AssemblyInfo.cs
  Server/Server.Tests/Server.Tests.csproj
  Server/Server.Tests/UnitTest1.cs
  Server/Server.Tests/packages.config
  Server/Server.sln
  Server/ServerTest/Properties/AssemblyInfo.cs
  Server/ServerTest/ServerTest.csproj
  Server/ServerTest/UnitTest1.cs
  Server/ServerTest/packages.config
Labels: backend, test

#25 Created the Mechanic Client View
  MechanicClient/MechanicClient/Details.png
  MechanicClient/MechanicClient/Images/Deatils.png
  MechanicClient/MechanicClient/Images/Garage.png
  MechanicClient/MechanicClient/Images/Registered.png
  MechanicClient/MechanicClient/Images/Repair.png
  MechanicClient/MechanicClient/Images/Repaired.png
  MechanicClient/MechanicClient/Images/Status.png
  MechanicClient/MechanicClient/MainWindow.xaml
  MechanicClient/MechanicClient/MechanicClient.csproj
  MechanicClient/MechanicClient/Registered.png
  MechanicClient/MechanicClient/Repair.png
  MechanicClient/MechanicClient/Repaired.png
  MechanicClient/MechanicClient/Status.png
  MechanicClient/MechanicClient/Views/AvailableJobs.xaml
  MechanicClient/MechanicClient/Views/AvailableJobs.xaml.cs
  MechanicClient/MechanicClient/Views/Job.xaml
  MechanicClient/MechanicClient/Views/Job.xaml.cs
Labels: frontend

#27 Created the model for the Mechanic Client
  MechanicClient/MechanicClient/Models/Job.cs
Labels: frontend

#29 Created the ViewModel
  MechanicClient/MechanicClient/App.xaml
  MechanicClient/MechanicClient/Commands/EditJobCommand.cs
  MechanicClient/MechanicClient/Commands/SortItemsCommand.cs
  MechanicClient/MechanicClient/Commands/UpdateJobStatusCommand.cs
  MechanicClient/MechanicClient/Commands/UpdateViewCommand.cs
  MechanicClient/MechanicClient/Edit.png
  MechanicClient/MechanicClient/Images/Deatils.png
  MechanicClient/MechanicClient/Images/Details.png
  MechanicClient/MechanicClient/Images/Edit.png
  MechanicClient/MechanicClient/Images/Status.png
  MechanicClient/MechanicClient/MainWindow.xaml
  MechanicClient/MechanicClient/MainWindow.xaml.cs
  MechanicClient/MechanicClient/MechanicClient.csproj
  MechanicClient/MechanicClient/Models/Job.cs
  MechanicClient/MechanicClient/Models/JobEditModeGui.cs
  MechanicClient/MechanicClient/ViewModels/AvailableJobsViewModel.cs
  MechanicClient/MechanicClient/ViewModels/JobViewModel.cs
  MechanicClient/MechanicClient/ViewModels/MainViewModel.cs
  MechanicClient/MechanicClient/ViewModels/ViewModelBase.cs
  MechanicClient/MechanicClient/Views/AvailableJobs.xaml
  MechanicClient/MechanicClient/Views/AvailableJobs.xaml.cs
  MechanicClient/MechanicClient/Views/Job.xaml
  MechanicClient/MechanicClient/Views/Job.xaml.cs
Labels: frontend

#31 Created DataProvider for MechanicClient #30
  MechanicClient/MechanicClient/DataProviders/JobDataProvider.cs
  MechanicClient/MechanicClient/MechanicClient.csproj
  MechanicClient/MechanicClient/Models/DatabaseJob.cs
  MechanicClient/MechanicClient/Models/Job.cs
  MechanicClient/MechanicClient/ViewModels/AvailableJobsViewModel.cs
  MechanicClient/MechanicClient/ViewModels/JobViewModel.cs
  MechanicClient/MechanicClient/packages.config
Labels: frontend

#33 Recruiter dataprovider
  RecruiterClient/RecruiterClient/DataProviders/JobDataProvider.cs
  RecruiterClient/RecruiterClient/Models/DatabaseJob.cs
  RecruiterClient/RecruiterClient/Models/DatabaseJobList.cs
  RecruiterClient/RecruiterClient/Models/Job.cs
  RecruiterClient/RecruiterClient/RecruiterClient.csproj
  RecruiterClient/RecruiterClient/packages.config
Labels: frontend
